set_location:
  target:
    entity:
      integration: wisemirror
  fields:
    name:
      required: true
      example: "Madrid"
      selector:
        text:
    latitude:
      required: true
      example: 40.4168
      selector:
        number:
          min: -90
          max: 90
          step: any
          mode: box
    longitude:
      required: true
      example: -3.7038
      selector:
        number:
          min: -180
          max: 180
          step: any
          mode: box
